language: fr
lang: fr-FR
author: "Machou"
robots: "all"
date: 2026-01-06 14:30:00 +0200
published: true
draft: false
toc: false
url: "https://machou.github.io"
markdown: kramdown
markdown_ext: "markdown,mkdn,md"
theme: jekyll-theme-cayman

# https://dashboard.jekyllrb.com/
# plugins:

sass:
  style: compressed

# github_username: Machou

socials:
  GitHub: https://github.com/Machou
  GitLab: https://gitlab.com/Machou

navbar:
  - title: "Accueil"
    url: "/"
  - title: "Cr√©er un Hidden Service"
    url: "/comment-creer-hidden-service"
  - title: "PortSentry"
    url: "/comment-utiliser-portsentry"
  - title: "Fail2ban"
    url: "/comment-utiliser-portsentry"
  - title: "WoW PNJ LFR"
    url: "/wow-pnj-lfr"
  - title: "Standardiser ma Release"
    url: "/standardiser-ma-release"
  - title: "Statistiques EuroMillions"
    url: "/statistiques-euromillions"

github:
  is_project_page: true
